### ISSUE TITLE
Champion Screen

### ISSUE THREAD

**Issue by abramz** [abramz/champion-select#13]
As a user, after selecting a champion...

I should be able to see 
- [ ] Champion details and stats (#7)
- [ ] Champion spell details and stats (#15)

I should be able to (do)
- [ ] Change the champion's level (#14)
- [ ] Change the level of a champion's spell (#16)

**Comment by abramz** [comment]
- [ ] add item issues
- [ ] add rune issues
- [ ] add mastery issues
- [ ] add details to all issues w/o checkboxes (#7, #14, #15, #16)

~~\- [ ] add locale issue~~ moved to own issue

**Comment by abramz** [comment]
TODO: add rune issues

**Comment by abramz** [comment]
TODO: add mastery issues

**Comment by abramz** [comment]
TODO: add locale issue
